### ISSUE TITLE
Cant disable LootTables

### ISSUE THREAD

**Issue by Guhenriques** [GroupXyz2/minecraft#1]
I have disabled the useLootTables config since I don't want to spawn the structures around the chest, but it doesnt seem to work, these structures still appearing.

useLootTables: false
lootTables:
  simple_dungeon:
    name: minecraft:chests/simple_dungeon
    active: false
  abandoned_mineshaft:
    name: minecraft:chests/abandoned_mineshaft
    active: false
  end_city_treasure:
    name: minecraft:chests/end_city_treasure
    active: false

**Comment by GroupXyz2** [comment]
Hi, this config option only disables/enables the usage of loot tables instead of the loot section in the config, it doesn't have to do anything with the spawning of the structure, but i can add an option to disable the spawning of the structure :)

**Comment by GroupXyz2** [comment]
It's too big so i can't upload it here, but there you go!
https://www.spigotmc.org/resources/treasurehunt.115406/
